?start : expr+

?value : SYMBOL -> symbol 
			 | STRING -> string 
       | BOOL -> bool

?atom	 : value
       | number
			 | SYMBOL atom atom ->binop

number : INT
       | FLOAT

?list  : "[" expr (","expr)* "]"

?expr  : atom
			 | list
       | "(" expr ")"

// Terminais
SYMBOL.0  : /[-!+\/*@$%^&~<>?|\\\w=]+/
STRING    : /"[^"\\]*(\\[^\n\t\r\f][^"\\]*)*"/
INT.1     : /-?\d+/
FLOAT.2   : /-?\d+\.\d+/
BOOL.3	    : /#[tf]/

%ignore /\s+/
%ignore /;[^\n]*/
